qlib_init:
  provider_uri: "data"
  region: cn
market: &market csi300
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
  start_time: 2010-01-01
  end_time: 2025-07-01
  fit_start_time: 2010-01-01
  fit_end_time: 2019-12-31
  instruments: *market
  cache_dir: "cache"
  enable_cache: true
port_analysis_config: &port_analysis_config
  strategy:
    class: EnhancedIndexingStrategy
    module_path: qlib.contrib.strategy
    kwargs:
      model: <MODEL>
      dataset: <DATASET>
      riskmodel_root: ./riskdata
      optimizer_kwargs:
        delta: 0.07 #total turnover limit
        lamb: 2.5 #risk aversion parameter
        b_dev: 0.03 #benchmark deviation limit
        f_dev: 0.02 #factor deviation limit
  backtest:
    start_time: 2023-01-01
    end_time: 2023-07-01
    account: 100000000
    benchmark: *benchmark
    exchange_kwargs:
      limit_threshold: 0.095
      deal_price: close
      open_cost: 0.0005
      close_cost: 0.0015
      min_cost: 5
task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      loss: mse
      colsample_bytree: 0.8879
      learning_rate: 0.2
      subsample: 0.8789
      lambda_l1: 205.6999
      lambda_l2: 580.9768
      max_depth: 8
      num_leaves: 210
      num_threads: 20
  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: CachedAlpha158
        module_path: qlib.contrib.data.cached_handler
        kwargs: *data_handler_config
      segments:
        train: [2010-01-01, 2019-12-31]
        valid: [2020-01-01, 2022-12-31]
        test: [2023-01-01, 2023-07-01]
  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        model: <MODEL>
        dataset: <DATASET>
    - class: SigAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        ana_long_short: False
        ann_scaler: 252
    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        config: *port_analysis_config
